### ISSUE TITLE
Some TODOs after merge PR #15

### ISSUE THREAD

**Issue by pokerfaceSad** [pokerfaceSad/GPUMounter#16]
Thanks for @ilyee add gang scheduling support in #15 which means gang scheduler can be selected when we add multi GPUs.

And still sth. need to fix:

* Add the relevant docs
* Add the relevant RESTful API

* allocator/allocator.go:159 log format error
* need to input all GPU uuids when unmount after gang mount

**Comment by ilyee** [comment]
I'll do this

**Comment by pokerfaceSad** [comment]
Done in #17 and 7036133177eabe2e32e03b33392df17dd8945dd1🎉🎉
