### ISSUE TITLE
More graceful dependency management

### ISSUE THREAD

**Issue by pokerfaceSad** [pokerfaceSad/GPUMounter#4]
GPU Mounter depends on `KubeletPodResources` api to get GPU usage from kubelet.

https://github.com/pokerfaceSad/GPUMounter/blob/f827c71c3a1c09fd7413b67629ccb6b1ac95f113/pkg/util/gpu/collector/collector.go#L11

The `KubeletPodResources` api is import from k8s.io/kubernetes directly.
Refer to [kubernetes/issues/79384](https://github.com/kubernetes/kubernetes/issues/79384) and [go/issues/32776](https://github.com/golang/go/issues/32776), it is necessary to add require directives for matching versions of all of the subcomponents.

https://github.com/pokerfaceSad/GPUMounter/blob/f827c71c3a1c09fd7413b67629ccb6b1ac95f113/go.mod#L14-L39

**Comment by pokerfaceSad** [comment]
But refer to k8s-device-plugin and gpu-manager.

https://github.com/NVIDIA/k8s-device-plugin/blob/e8de9ba1bf030a8a385250755d23b6ca93b3a587/go.mod#L35

https://github.com/tkestack/gpu-manager/blob/15b913864e4d24a5a5180da3aa3875acac70801c/go.mod#L34

Import from k8s.io/kubelet will be more graceful.

**Comment by pokerfaceSad** [comment]
Thx for help from smart @InfluencerNGZK 👍👍👍

**Comment by InfluencerNGZK** [comment]
Yeah, dependencies really matter in writing Golang codes. I think everyone who wants to manage their dependencies in a graceful way should read the instructions below first.
https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dependency-management-for-the-serious-or-reluctant-user

**Comment by InfluencerNGZK** [comment]
> Thx for help from smart @InfluencerNGZK 👍👍👍

My pleasure bro :)

**Comment by pokerfaceSad** [comment]
`KubeletPodResources ` api was move into kubelet staging repo in this commit https://github.com/kubernetes/kubelet/commit/86eb1718688718f2dc89039d15b4685d87ffd159#diff-56d5ab786db1c40992aafb5f4b6218ab4633eece4e557cb04b40526099afa3cc

So we can import `KubeletPodResources ` api  from kubelet staging repo only if k8s ≥ 1.20 😑😑😑
